### ISSUE TITLE
Red gem launches player off map

### ISSUE THREAD

**Issue by melissajames04** [MisterMiao/TOEBugs#10]
**Description:**
Red gem on the top of the elevator launches player that collects it off of map.

**Severity (1-3) or enhancement**
3 

**Steps to reproduce**
-Jump on the elevator
-Collect the gem
-Launch off the map

**Build # 0.8**

**Comment by acaskanette** [comment]
Cause is the elevator's momentum + jump momentum. Will assign Dylan to fix.

**Comment by NorthernTracker** [comment]
I halved the speed of the elevator, should slow it down enough that it won't launch people
