### ISSUE TITLE
Spawned in are full of colliders and had trouble navigating

### ISSUE THREAD

**Issue by melissajames04** [MisterMiao/TOEBugs#11]
**Description:**
Fell in lava and respawned on the other side of the locked bridge, colliders caused problems in getting out of the spawned area.

**Severity (1-3) or enhancement**
2

**Steps to reproduce**
-Go to the last locked bridge
-Go into the lava by the right of the bridge
-The player will respawn on the other side, with very tight colliders

**Build # 0.8**

**Comment by acaskanette** [comment]
Should be avoidable by respawn system. Will rework that landing area for people who explore it, though.

**Comment by MisterMiao** [comment]
Respawn system fixes
