### ISSUE TITLE
By pass pressure plates by using hay bales as step

### ISSUE THREAD

**Issue by melissajames04** [MisterMiao/TOEBugs#12]
**Description:**
Could stand on hay bales to get out of gated areas, bypassing the pressure plate.

**Severity (1-3) or enhancement**
3

**Steps to reproduce**
-Got to a gated area with hay bales
-Roll a hay bale up to the fence
-Jump on the hay bale 
-Jump to the other side of the fence

**Build # 0.8**

**Comment by acaskanette** [comment]
Intended to be able to jump off objects. Did cut off player and make pressure plate more obvious.
