### ISSUE TITLE
Constantly jumping upwards using wind tunnels

### ISSUE THREAD

**Issue by melissajames04** [MisterMiao/TOEBugs#13]
**Description:**
Can create wind tunnels while you are in the area and continuously keep jumping upwards.

**Severity (1-3) or enhancement**
3 

**Steps to reproduce**
-Create a wind tunnel while on the ground
-Hold down the jump button to jump
-While in the air create another wind tunnel
-Press the jump button again
-Keep doing this until you run out of mana

**Build # 0.8**

**Comment by acaskanette** [comment]
Nerfed. Much harder to do, but still fun.

**Comment by acaskanette** [comment]
Vertical nearly impossible, horizontal boosts now work.
