### ISSUE TITLE
Stuck inside mountain

### ISSUE THREAD

**Issue by melissajames04** [MisterMiao/TOEBugs#14]
**Description:**
Got stuck in mountain just after Janwa’s house and had to reset the game.

**Severity (1-3) or enhancement**
1 – Game breaking bug

**Steps to reproduce**
-Create wind tunnel
-Jump towards the mountain
-Just keep creating wind tunnels to move player forward

**Build # 0.8**

**Comment by acaskanette** [comment]
Should be okay after nerf.

**Comment by acaskanette** [comment]
Unable to reproduce on latest build.
