### ISSUE TITLE
Did not die after falling in lava

### ISSUE THREAD

**Issue by melissajames04** [MisterMiao/TOEBugs#16]
**Description:**
Fell in the lava near Janwa’s hut and did not die.

**Severity (1-3) or enhancement**
2
**
Steps to reproduce**
-Make a wind tunnel 
-Both players jump into the lava
-Able to walk around in lava

**Build # 0.8**

**Comment by acaskanette** [comment]
mister Miao working on it

**Comment by MisterMiao** [comment]
Respawn system fixes
