### ISSUE TITLE
Easy to miss tutorials in gameplay

### ISSUE THREAD

**Issue by melissajames04** [MisterMiao/TOEBugs#17]
**Description:**
Tutorials would only appear when you enter the area for the first time, and would not appear again when the area is re-entered.  This made it very easy to bypass tutorial information.

**Severity (1-3) or enhancement**
2

**Steps to reproduce**
-Quickly run by a tutorial point
-Re-enter tutorial point and nothing will appear

**Build # 0.8**

**Comment by acaskanette** [comment]
Fixed.
