### ISSUE TITLE
Player spawned inside switch and got stuck

### ISSUE THREAD

**Issue by melissajames04** [MisterMiao/TOEBugs#2]
**Description:**
Player respawned after death inside switch by the single log bridge.  This resulted in the player being stuck for several minutes until a lucky sequence of events happened to wiggle the player free.

**Severity (1-3) or enhancement**
1 – Game breaking bug

**Steps to reproduce**
-Lower the single log bridge
-Fall off around 1/3 of the way across the bridge
-Respawn on the switch

**Build # 0.8**

**Comment by acaskanette** [comment]
Will explore duplication: once respawn system in placed will likely be fixed.

**Comment by MisterMiao** [comment]
Respawn system fixes
