### ISSUE TITLE
Problems/Inconsistency opening gates

### ISSUE THREAD

**Issue by melissajames04** [MisterMiao/TOEBugs#3]
**Description:**
Gates not opening consistently within the game.  First gate could be opened from one side and not reopened from inside the bounds.

**Severity (1-3) or enhancement**
2 

**Steps to reproduce**
-Open the first gate
-Enter the gated area
-Try to reopen gate after it closes behind the player

**Build # 0.8**

**Comment by acaskanette** [comment]
The bounds for triggering the switch are smaller than the button prompt. Also intended to use a different gate to leave the yard. should not be able to hit switch through the gate. Have moved the switch and button prompt slightly so it will not appear on the inside of the yard.
