### ISSUE TITLE
Able to use magic abilities to open gates

### ISSUE THREAD

**Issue by melissajames04** [MisterMiao/TOEBugs#4]
**Description:**
Able to use magic abilities to open gates, which did not seem intentional nor could it be used every time.

**Severity (1-3) or enhancement**
2

**Steps to reproduce**
-Go up to the gate opening
-Use the Quake Strike ability standing flush against the gate
-Gate opens

**Build # 0.8**

**Comment by acaskanette** [comment]
We believe this to be coincidental. We think a mud ball accidentally hit the switch at the same time. If we can reproduce, we will address.

**Comment by acaskanette** [comment]
Unable to reproduce.
