### ISSUE TITLE
Spawning after falling lava allows bypassing locked bridges

### ISSUE THREAD

**Issue by melissajames04** [MisterMiao/TOEBugs#5]
**Description:**
At the second locked bridge, both players jumped in the lava and were spawned on the other side of the bridge.  This caused the bridge to unlock, though no intentional actions were taken to unlock it.

**Severity (1-3) or enhancement**
2

**Steps to reproduce**
-Go to the last locked bridge
-Both players jump at the same time to the right of the bridge
-Should spawn on other side of the bridge

**Build # 0.8**

**Comment by acaskanette** [comment]
Will be fixed by respawn system.

**Comment by MisterMiao** [comment]
Respawn system fixes
