### ISSUE TITLE
Stuck in mountain crevice

### ISSUE THREAD

**Issue by melissajames04** [MisterMiao/TOEBugs#6]
**Description:**
Stuck in a crevices by the Cathedral looking building on the other side of the single log bridge and had to button bash to get out.

**Severity (1-3) or enhancement**
1 – Game breaking bug

**Steps to reproduce**
-Go to the other side of the single log bridge
-Go to the left of the Cathedral looking building
-Will get stuck in the hole on that side

**Build # 0.8**

**Comment by acaskanette** [comment]
Added new invisi-walls to prevent trapping at this location.
