### ISSUE TITLE
Walk around end of gate without falling in lava

### ISSUE THREAD

**Issue by melissajames04** [MisterMiao/TOEBugs#7]
**Description:**
Able to bypass the gate by walking around due to improperly placed colliders.  

**Severity (1-3) or enhancement**
3 

**Steps to reproduce**
-Go to the gated area to the left of the stone bridge
-Walk towards the lava
-Pivot quickly around the end of the fence by the lava
-Should make it to the other side without dying

**Build # 0.8**

**Comment by acaskanette** [comment]
Added another fence to the fenceline and extended it slightly past the fence.
