### ISSUE TITLE
Can bypass areas by dying and spawning next to partner

### ISSUE THREAD

**Issue by melissajames04** [MisterMiao/TOEBugs#8]
**Description:**
Could bypass the gate if one player made it to the other side by jumping in the lava and respawning in the correct location.

**Severity (1-3) or enhancement**
3

**Steps to reproduce**
-One player makes if over the fence 
-The other player jumps in the lava
-Player that died will be spawned inside the fenced area

**Build # 0.8**

**Comment by acaskanette** [comment]
Will be fixed by respawn system.

**Comment by MisterMiao** [comment]
Respawn system fixes
